### ISSUE TITLE
Add fields to EtcdStorage Spec for name and namespace of proxy etcd certs Secret/ConfigMap

### ISSUE THREAD

**Issue by xmudrii** [xmudrii/etcdproxy-controller#30]
We should allow API server operators to provide the name and namespace of the Secret and ConfigMap where proxy etcd certs are going to be stored.

The names can be part of the EtcdStorage Spec, and operators could provide them such as:
```yaml
apiVersion: etcd.xmudrii.com/v1alpha1
kind: EtcdStorage
metadata:
  name: etcd-name # this is the name of the API group and the etcd namespace. As we’re building the service’s name based of this name, we have to limit this name not to be longer than 64-5 character (because we’re using ‘etcd-’ prefix in service’s name). The name must consist only of lower-case characters, ‘-’ and ‘.’.
spec:
  serverCACert: # CA certificate used to verify serving certificates. Stored in ConfigMaps specified by namespace/name pairs below. ConfigMaps along with RBAC rules allowing EtcdProxyController to access specified ConfigMaps must exist prior to creating an ‘EtcdStorage’ instance.
    - name: etcd-serving-ca
      namespace: foo
  clientCert: # Client certificate for accessing etcdproxy. Stored in Secrets specified by namespace/name pairs below. Secrets along with RBAC rules allowing EtcdProxyController to access specified Secrets must exist prior to creating an ‘EtcdStorage’ instance.
    - name: etcd-client-cert
      namespace: foo
```

Once implemented, we need to:
* Update [the `03-sample-apiserver-deployment.yaml` manifest](https://github.com/xmudrii/etcdproxy-controller/blob/master/artifacts/deployment/03-sample-apiserver-deployment.yaml#L7) to use the fields,
* Update [the `example-etcdstorage.yaml` manifest](https://github.com/xmudrii/etcdproxy-controller/blob/master/artifacts/etcdstorage/example-etcdstorage.yaml) to reflect changes.
